export enum SELECT_TOOLS {
    RECTANGLE = 1,
    LINE = 2,
    PENCIL = 3,
    BRUSH = 4,
    ELLIPSE = 5,
    POLYGONE = 6,
    ERASE = 7,
    FILL = 8,
    DROPPER = 9,
    SPRAY = 10,
    FEATHER = 11,
    STAMP = 12,
    SELECTION = 13,
    BUCKET = 14,
    NONE = 15,
    GRID = 16,
}
